//
//  ImageDetailPresenter.swift
//  CodeChallenge
//
//  Created by Cesar Brenes on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageDetailPresentationLogic {
    func presentUIInformation(response: ImageDetail.UIInformation.Response)
}

class ImageDetailPresenter: ImageDetailPresentationLogic {
    weak var viewController: ImageDetailDisplayLogic?
    
    func presentUIInformation(response: ImageDetail.UIInformation.Response) {
        viewController?.displayUIInformation(viewModel: ImageDetail.UIInformation.ViewModel(url: URL(string: response.url)))
    }
}
