//
//  ImageDetailModels.swift
//  CodeChallenge
//
//  Created by Cesar Brenes on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ImageDetail {
    enum UIInformation {
        struct Request {
        }
        struct Response {
            var url: String
        }
        struct ViewModel {
            var url: URL?
        }
    }
}
