//
//  ImageDetailRouter.swift
//  CodeChallenge
//
//  Created by Cesar Brenes on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ImageDetailRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ImageDetailDataPassing {
    var dataStore: ImageDetailDataStore? { get set}
}

class ImageDetailRouter: NSObject, ImageDetailRoutingLogic, ImageDetailDataPassing {
    weak var viewController: ImageDetailViewController?
    var dataStore: ImageDetailDataStore?
    
}
