//
//  ImageDetailViewController.swift
//  CodeChallenge
//
//  Created by Cesar Brenes on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageDetailDisplayLogic: class {
    func displayUIInformation(viewModel: ImageDetail.UIInformation.ViewModel)
}

class ImageDetailViewController: UIViewController, ImageDetailDisplayLogic {
    var interactor: ImageDetailBusinessLogic?
    var router: (NSObjectProtocol & ImageDetailRoutingLogic & ImageDetailDataPassing)?
    
    // MARK: Object lifecycle
    @IBOutlet weak var urlImageView: CustomImageViewWithCache!
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ImageDetailInteractor()
        let presenter = ImageDetailPresenter()
        let router = ImageDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        title = LocalizationHelper.photoDetail.localizedString()
        requestUIInformation()
    }
    
    /**
     In the case the download is in progress and the user decided to go back, the app will stop the download
     */
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        urlImageView.dataTask?.cancel()
    }
    
    // MARK: Request Methods
    func requestUIInformation() {
        let request = ImageDetail.UIInformation.Request()
        interactor?.requestUIInformation(request: request)
    }
    
    // MARK: Display Methods
    func displayUIInformation(viewModel: ImageDetail.UIInformation.ViewModel) {
        urlImageView.downloadImage(url: viewModel.url)
    }
    
}
