//
//  ImageDetailInteractor.swift
//  CodeChallenge
//
//  Created by Cesar Brenes on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageDetailBusinessLogic {
    func requestUIInformation(request: ImageDetail.UIInformation.Request)
}

protocol ImageDetailDataStore {
    var url: String? { get set }
}

class ImageDetailInteractor: ImageDetailBusinessLogic, ImageDetailDataStore {
    var presenter: ImageDetailPresentationLogic?
    var url: String?
    
    func requestUIInformation(request: ImageDetail.UIInformation.Request) {
        if let url = url {
            presenter?.presentUIInformation(response: ImageDetail.UIInformation.Response(url: url))
        }
    }
}
