//
//  ImagesListRouter.swift
//  CodeChallenge
//
//  Created by Cesar Brenes on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ImagesListRoutingLogic {
    func presentAlertController(alertController: UIAlertController)
    func presentDetailViewController(index: Int)
}

protocol ImagesListDataPassing {
    var dataStore: ImagesListDataStore? { get }
}

class ImagesListRouter: NSObject, ImagesListRoutingLogic, ImagesListDataPassing {
    weak var viewController: ImagesListViewController?
    var dataStore: ImagesListDataStore?
    
    func presentAlertController(alertController: UIAlertController) {
        viewController?.present(alertController, animated: true, completion: nil)
    }
    
    func presentDetailViewController(index: Int) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        if let viewController = storyboard.instantiateViewController(withIdentifier: String(describing: ImageDetailViewController.self)) as? ImageDetailViewController {
            let url = dataStore?.getURL(index: index)
            viewController.router?.dataStore?.url = url
            self.viewController?.navigationController?.pushViewController(viewController, animated: true)
        }
    }
}
