//
//  ImagesListModels.swift
//  CodeChallenge
//
//  Created by Cesar Brenes on 19/2/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ImagesList {
  // MARK: Use cases
  
  enum DataSource {
    struct Request {
        var isRefreshAction: Bool
    }
    struct Response {
        var numberOfPreviousItems: Int
        var items: [ImageItem]?
        var totalNumberOfElements: Int
        var errorFound: APIError?
    }
    struct ViewModel {
        struct Succes {
            var numberOfPreviousItems: Int
            var displayObjects: [DisplayObject]
            var totalNumberOfElements: Int
            var indexPathToInsert: [IndexPath]?
            struct DisplayObject {
                var thumbnailUrl: URL?
            }
        }
        
        struct ErrorFound {
            var title: String
            var message: String
            var leftButtonTitle: String
            var rightButtonTitle: String
            var tableViewErrorMessage: String
        }
        
        struct EmptyState {
            var message: String
        }
    }
  }
}
